---
title: "Trabajo de ivestigacion"
subtitle: "Centrarse en lo siguiente /n "
output:
  pdf_document: default
  html_document: default
---

# Caratula

# Resumen 1 

- Objetivo
- Metodologia
  - Modelo econometrico
  - Metodo
  - variables
- Resultados 

# Introduccion 2-3

- Descripcion historica de las variables 
- Identificacion del problema 
- Planteamiento del probleam 
  - Objetivos
  - Importancia del problema

# antecedentes teoricos 2 3 

- Relacion teorica de las variables 
   - libros investigaciones

# Antecedentes empiricos 2 - 3

- Investigaciones anteriores 
  - Relacion entre las variables

# Hechos estilizados 2


- Tendencias, comportamientos generales de las variables
  - Graficos en el tiempo por cada variables
- Tablas por periodos del comportamiento promedio de las variables


- Basados en papers del bcrp, 
  - Estadisticas 
  - Cuadros, 
  - Graficos (barras, lineales , histogramas , scatter plot) 
    - Muestran indicios 
- Caracteristicas relevantes de las variables 

# Modelo teorico 2

- $y  = f(variables)$ 
  - $lngdp = lnce + e$
- El porque la eleccion del modelo 

# Hipotesis 1

- Respuesta abticipada, 
  - Coportamiento causal entre las variables 

# Metodologia  2-3

- Datos
  - caracteristicas de las variables
  - Significado de las variables    
  - Fuente de datos
  - signo esperado
- Modelo econometrico (VAR)
- Metodo(funcional, correlacional?)
- Decribir el modelo econonetrico 

# Resultados 5

- Estimaciones 
  - Tablas 
  - Grafico  
  - Preubas de hupotesis 
  - Nivel de confiabilidad de los resultados    
- Conclusiones 

# Recomendaciones 

- Recomendaciones de politica

# Referencia bibliografica 
